#ifndef ENUMS_H
#define ENUMS_H

enum OPERATIONS {DP0, DP1, DP2, DP3, DP4, DP5, DP6, DP7, UNKNOWOP, READ = 9, WRITE = 10, OUTDIS = 11, STB12, STB13, STB14, STB15};
enum SELECTION {M0, M1, M2, M3, M4, M5, M6, M7} ;
enum ENABLEDIS {DISABLE_MEM= 0, ENABLE_MEM = 1} ;

//Establecemos valores por default
OPERATIONS OP_MODE = READ; 
SELECTION MEMORY = M0; 
ENABLEDIS ED_MEM = ENABLE_MEM;

#endif
